spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/grenciador_estoque
        username: postgres
        password: 1412
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true